esphome:
  name: m5cores3
  friendly_name: M5CoreS3
  platformio_options:
    board_build.f_cpu : 240000000L
  libraries:
    - m5stack/M5GFX@^0.1.11
    - m5stack/M5Unified@^0.1.11

# packages:
  # m5stack.cores3-voice-assistant: github://Forairaaaaa/cores3_esphome/m5stack-cores3.yaml@main
  # m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TDIsGOLfYDNgo3DIhLspajS/VFuDlzwJ1n7N1CnJ5eI="

ota:
  password: "148ed3bd22185832c75c272f52167c27"

wifi:
  ssid: "GL-AXT1800-06a"
  password: "m5stack001"
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Cores3 Fallback Hotspot"
    password: "Vfp1Cj2o6uFW"

captive_portal:
    


psram:
  mode: octal
  speed: 80MHz


external_components:
  - source:
      type: local
      path: "./components"
    components: [ board_m5cores3, m5cores3_audio, m5cores3_display ]
    refresh: 0s
  # - source:
  #     type: git
  #     url: https://github.com/Forairaaaaa/cores3_esphome
  #   components: [ board_m5cores3, esp_adf ]
  #   refresh: 0s

board_m5cores3:
m5cores3_audio:
  id: m5cores3_audio_1


display:
  - platform: m5cores3_display
    # model: ili9342
    # dc_pin: 27
    # reset_pin: 33



switch:
- platform: template
  name: "M5CoreS3 Display Test"
  id: switch_m5cores3_display_test
  restore_mode: "RESTORE_DEFAULT_OFF"
  turn_on_action:
    - logger.log: "show on shit"
  turn_off_action:
    - logger.log: "show off shit"

