substitutions:
  name: m5stack-atom-echo
  friendly_name: M5Stack Atom Echo
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 0RSOubR4wGKOqrEGyRGKp4y3qBzaOwzxzXY5Zc5HTAM=


wifi:
  ssid: "GL-AXT1800-06a"
  password: "m5stack001"
