esphome:
  name: m5cores3
  friendly_name: M5CoreS3
  libraries:
    - m5stack/M5GFX@^0.1.11
    - m5stack/M5Unified@^0.1.11
  on_boot:
    lambda:
      M5.begin();

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/Forairaaaaa/cores3_esphome
      ref: ver1
    components: [ board_m5cores3 ]

board_m5cores3:
  id: board_m5cores3_1


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DxZPw6qF/McYERdnXq2knr1BKfsqtPk/WW3muPAh+Kk="

ota:
  password: "0eb929fd7530eda89500a0bde0ae1fbf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Cores3 Fallback Hotspot"
    password: "1IsIshzc8Y5j"

captive_portal:
    