esphome:
  name: m5cores3
  friendly_name: M5CoreS3
  libraries:
    - m5stack/M5GFX@^0.1.11
    - m5stack/M5Unified@^0.1.11
  on_boot:
    lambda:
      M5.begin();

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz



external_components:
  - source:
      type: git
      url: https://github.com/Forairaaaaa/cores3_esphome
      ref: ver1
    components: [ board_m5cores3 ]

board_m5cores3:
  id: board_m5cores3_1



# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lRdTPwdT4894Prkbk0hM0nIiCU/ZqPLlKKYxj2ZnKR0="

ota:
  password: "a7225cbff87b7797cb092b0b71b69a4c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.2.140
    gateway: 192.168.2.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Cores3 Fallback Hotspot"
    password: "k9NQ3aRdLcWw"

captive_portal:



spi:
  clk_pin: 36
  mosi_pin: 37

# Display
display:
  - platform: ili9xxx
    model: ILI9342
    dc_pin: 35
    cs_pin: 3
    lambda: |-
      it.fill(Color::BLACK);
      it.filled_circle(140, 120, 20, Color(255, 255, 255));
    


switch:

# Lcd Backlight 
- platform: template
  name: "LCD Backlight"
  id: switch_lcd_backlight
  restore_mode: "RESTORE_DEFAULT_ON"
  turn_on_action:
    - lambda:
        M5.Display.setBrightness(127);
  turn_off_action:
    - lambda: |-
        M5.Display.setBrightness(0);

