
esphome:
  name: m5cores3
  friendly_name: M5CoreS3
  libraries:
    - m5stack/M5GFX@^0.1.11
    - m5stack/M5Unified@^0.1.11

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz



external_components:
  - source:
      type: git
      url: https://github.com/Forairaaaaa/cores3_esphome
      ref: ver4
    components: [ board_m5cores3 ]

board_m5cores3:
  id: board_m5cores3_1







# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ZzXGSFpPyCaeL2dSbdTAYQT8KyVIc1lDr6Ty3A1mzN4="

ota:
  password: "f0c70a51f8f1ce2e81aa16f28e44517a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Cores3 Fallback Hotspot"
    password: "Y0owxrmIgA7Z"

captive_portal:
    






# 
# Display
# 
spi:
  clk_pin: 36
  mosi_pin: 37

display:
  - platform: ili9xxx
    model: ILI9342
    dc_pin: 35
    cs_pin: 3
    id: m5cores3_lcd
    data_rate: 40MHz
    update_interval: never
    invert_colors: false
    






# 
# Mic
# 
i2s_audio:
  i2s_lrclk_pin: GPIO33
  i2s_bclk_pin: GPIO34
  id: m5cores3_i2s

microphone:
  - platform: i2s_audio
    adc_type: external
    i2s_din_pin: GPIO14
    pdm: false
    i2s_audio_id: m5cores3_i2s
    id: m5cores3_mic

# 
# Speaker
# 
speaker:
  - platform: i2s_audio
    dac_type: external
    i2s_dout_pin: GPIO13
    mode: mono
    i2s_audio_id: m5cores3_i2s
    id: m5cores3_spk





voice_assistant:
  microphone: m5cores3_mic
  speaker: m5cores3_spk




switch:

# Lcd Backlight 
- platform: template
  name: "LCD Backlight"
  id: switch_lcd_backlight
  restore_mode: "RESTORE_DEFAULT_ON"
  turn_on_action:
    - lambda:
        M5.Display.setBrightness(127);
  turn_off_action:
    - lambda: |-
        M5.Display.setBrightness(0);

# VA test 
- platform: template
  name: "VA shit"
  id: switch_va
  turn_on_action:
    - voice_assistant.start:
          silence_detection: true
  turn_off_action:
    - voice_assistant.stop:

