esphome:
  name: m5cores3
  friendly_name: M5CoreS3
  libraries:
    - m5stack/M5GFX@^0.1.11
    - m5stack/M5Unified@^0.1.11

esp32:
  board: esp32-s3-devkitc-1
  # flash_size: 16MB
  framework:
    type: arduino


# psram:
#   mode: octal
#   speed: 80MHz


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dce6ZIlW2LEpwjxuJs+RPUuwe1cMk47zGtJNBgi1+p0="

ota:
  password: "d337432fa1a3a1155e5563aa3e254551"

wifi:
  ssid: "GL-AXT1800-06a"
  password: "m5stack001"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Cores3 Fallback Hotspot"
    password: "bGycp2AoOkrN"

captive_portal:
    


# external_components:
#   - source:
#       type: git
#       url: https://github.com/Forairaaaaa/cores3_esphome
#       # ref: ver4
#     components: [ board_m5cores3 ]
#     refresh: 0s

# board_m5cores3:






# # 
# # Mic
# # 
# i2s_audio:
#   i2s_lrclk_pin: GPIO33
#   i2s_bclk_pin: GPIO34
#   id: m5cores3_i2s

# microphone:
#   - platform: i2s_audio
#     adc_type: external
#     i2s_din_pin: GPIO14
#     pdm: false
#     i2s_audio_id: m5cores3_i2s
#     id: m5cores3_mic

# # 
# # Speaker
# # 
# speaker:
#   - platform: i2s_audio
#     dac_type: external
#     i2s_dout_pin: GPIO13
#     mode: mono
#     i2s_audio_id: m5cores3_i2s
#     id: m5cores3_spk





# voice_assistant:
#   microphone: m5cores3_mic
#   speaker: m5cores3_spk
#   use_wake_word: true
#   noise_suppression_level: 2
#   auto_gain: 31dBFS
#   volume_multiplier: 2.0
#   # vad_threshold: 3
#   on_listening:
#     - logger.log: "on listening shit"
#   on_wake_word_detected:
#     - logger.log: "wake up shit"
#   on_client_connected:
#     - voice_assistant.start_continuous:
#   on_client_disconnected:
#     - voice_assistant.stop:




# switch:

# # Lcd Backlight 
# - platform: template
#   name: "M5CoreS3 VA Test"
#   id: switch_m5cores3_va_test
#   restore_mode: "RESTORE_DEFAULT_ON"
#   turn_on_action:
#     - voice_assistant.start_continuous:
#   turn_off_action:
#     - voice_assistant.stop:



